package com.coursehub.enums;

public enum NotificationType {
    COMMENT_LIKED,
    COMMENT_REPLIED,
    NOTIFICATION_HIDDEN,
    NOTIFICATION_SHOWN,
    USER_WARNED,
    USER_BANNED,
    USER_UNBANNED,
    ADMIN_ANNOUNCEMENT,
    COMMENT_ADDED,
    REVIEW_ADDED,
    PAYMENT_SUCCESS,
    LESSON_ADDED,
    REPORT_PROCESSED,
    DISCOUNT_AVAILABLE,
    FEEDBACK_REPLIED
} 