package com.coursehub.enums;

public enum NotificationType {
    COMMENT_LIKED,
    COMMENT_REPLIED,
    CONTENT_HIDDEN,
    CONTENT_SHOWN,
    NEW_COURSE_AVAILABLE,
    ENROLLMENT_CONFIRMED,
    COURSE_COMPLETED,
    CERTIFICATE_ISSUED,
    REPORT_PROCESSED,
    DISCOUNT_AVAILABLE,
    COURSE_PROMOTION,
    SYSTEM_MAINTENANCE,
    USER_WARNED,
    USER_BANNED,
    USER_UNBANNED,
    ADMIN_ANNOUNCEMENT,
    PASSWORD_CHANGED,
    FEEDBACK_REPLIED
}

