version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=CourseHub
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  coursehub-backend:
    container_name: coursehub-backend
    image: kl3init/coursehub:latest  # Thay your-username bằng tên Docker Hub của bạn
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

networks:
  default:
    name: coursehub-backend

volumes:
  mysql_data:
  redis_data: