version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add: [SYS_NICE]
    restart: always
    environment:
      - MYSQL_DATABASE=CourseHub
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coursehub-network

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coursehub-network

networks:
  coursehub-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
