version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add: [SYS_NICE]
    restart: always
    environment:
      - MYSQL_DATABASE=CourseHub
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coursehub-network

  coursehub-backend:
    container_name: coursehub-backend
    image: kl3init/coursehub:latest
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - coursehub-network
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coursehub-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - coursehub-network
    depends_on:
      - coursehub-backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    networks:
      - coursehub-network

networks:
  coursehub-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: