spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3307/CourseHub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dat123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  aws:
    credentials:
      access-key: AKIAVRKAPVE6FGFGBTNN
      secret-key: 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
    region: ap-southeast-2
    s3:
      bucket: course-hub-resourses