spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:3000/auth/google/callback
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  datasource:
    url: jdbc:p6spy:mysql://localhost:3307/CourseHub
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Cấu hình p6spy trực tiếp trong application.yml
  p6spy:
    config:
      # Định dạng log (SingleLineFormat để dễ đọc)
      logMessageFormat: com.p6spy.engine.spy.appender.SingleLineFormat
      # Appender để ghi log vào Slf4j (mặc định trong Spring Boot)
      appender: com.p6spy.engine.spy.appender.Slf4jLogger
      # Không log các truy vấn không quan trọng (tuỳ chọn)
      exclude: >
        select 1,^mysql: .*
      # Bật logging (mặc định là true)
      logEnabled: false
      # Tắt log stack trace nếu không cần (tuỳ chọn)
      stacktrace: false
      # Đường dẫn file log (tuỳ chọn, để log vào file thay vì console)
      # logFile: logs/p6spy.log

  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-southeast-2
    s3:
      bucket: course-hub-resourses

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000

  mail:
    host: smtp.gmail.com
    port: 587
    username: it4beginer@gmail.com
    password: eywvbyghvnkthibx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: WaVbZbGzZMYGHUjNYrh87xGyib8ivGWndlsf4bsX2mB47MbdsUTwf2Dsv1TPuBG+
  expiration: 2592000000

sepay:
  secret-key: ${SEPAY_WEBHOOK_APIKEY}

bank:
  bank-number: 22226376000
  bank-code: TPBank
  account-holder: NHU DINH NHAT

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    # Bật logging cho p6spy
    p6spy: INFO