spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3307/CourseHub?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dat123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   # hoặc validate/create/create-drop tùy môi trường
    show-sql: true
    properties:
      hibernate:
        format_sql: true
