server:
  port: 8080

spring:
  application:
    name: coursehub-backend
  profiles:
    active:
      - dev


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO




