spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/CourseHub
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#redis la mot bo luu tru doc lap voi dang key value, dung de luu tru tam thoi mot so thong tin khi minh chua muon luu vao database
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#  cache:
#    type: redis
#    redis:
#      time-to-live: 600000